(TeX-add-style-hook
 "main-fullversion"
 (lambda ()
   (TeX-run-style-hooks
    "macros")
   (LaTeX-add-labels
    "sec_bayesInfer"
    "sec_setup"
    "subsec_emgs"
    "equ_utility"
    "subsec_emls"
    "sec_smoo"
    "def_smoo"
    "lem_hexpmech_privacy"
    "subsec_accuracy_lap"
    "subsec_accuracy_global"
    "subsec_accuracy_smoo"
    "subsec_accuracy_tradeoff"
    "fig_sensitivity"
    "fig_efficiency"
    "sec_experiment"
    "subsec_effi"
    "subsec_experiment_accuracy"
    "fig_beta_hellinger"
    "fig_dirichlet_hellinger"
    "fig_dirichlet_hellinger_l1"
    "subsec_vs_variables"
    "subsubsec_vs_datasize"
    "fig_vs_datasize"
    "subsubsec_vs_dimension"
    "fig_vs_dimension"
    "subsubsec_vs_variance"
    "fig_vs_variance"
    "subsubsec_vs_prior"
    "fig_vs_prior"
    "subsubsec_vs_prior_variance"
    "fig_vs_prior_variance"
    "subsec_experiment_privacy"
    "fig_privacy")
   (LaTeX-add-bibliographies
    "bayesian.bib"))
 :latex)

